LANG = {
    "en": {
        "title": "DCF Market Sensing Tool · AI Edition",
        "subtitle": "P₀ = EPS × (1+g)ⁿ × PE_exit / (1+r)ⁿ",
        "lang_label": "Language",
        "params": "Parameters",
        "price": "Current Stock Price ($)",
        "eps": "Current EPS — TTM ($)",
        "g": "Expected Annual Growth Rate (g %)",
        "r": "Required Annual Return (r %)",
        "n": "Forecast Years (n)",
        "pe_exit": "Exit PE Multiple",
        "mode": "Analysis Mode",
        "mode_reverse": "A — What is the market betting on?",
        "mode_fair": "B — What is the stock worth?",
        "mode_sense": "C — Sensitivity matrix",
        "implied_g": "Market Implied Growth",
        "your_g": "Your Growth Assumption",
        "fair_val": "Fair Value",
        "premium": "Premium / Discount",
        "verdict_high": "⚠️  Market more optimistic than you ({ig:.1f}% implied vs {g:.1f}% yours). If growth only hits {g:.1f}%, stock faces downward pressure.",
        "verdict_low": "✅  Market more conservative than you ({ig:.1f}% implied vs {g:.1f}% yours). If growth hits {g:.1f}%, stock has upside.",
        "eps_path": "EPS Path — Year by Year",
        "year": "Year", "eps_col": "EPS ($)", "exit_price": "Exit Price ($)", "pv": "PV Today ($)",
        "terminal": "Year {n} exit = ${fp:.2f} (EPS ${fe:.2f} × {pe}x) → discounted = ${pv:.2f} at {r:.0f}%/yr",
        "updown": "Upside / Downside vs Market",
        "sense_title": "Fair Value Matrix — Sensitivity",
        "sense_sub": "EPS=${eps:.2f} | r={r:.1f}% | n={n}yr | Price=${price:.2f}",
        "growth_axis": "g (%/yr)", "pe_axis": "Exit PE",
        "legend_up": "▲ Undervalued (>5%)", "legend_flat": "─ Fair range", "legend_down": "▼ Overvalued (>5%)",
        "how_to": "📋 How to use after earnings",
        "how_1": "1. EPS beat/miss → adjust EPS slider",
        "how_2": "2. Read management guidance → adjust g slider",
        "how_3": "3. Matrix fair value vs actual market reaction",
        "how_4": "4. Market drops but matrix = undervalued → buy signal",
        "how_5": "5. Market rallies but matrix = overvalued → priced in too much",
        "plot_title": "DCF Sensitivity  |  ${price:.2f}  EPS ${eps:.2f}  n={n}yr",
        "plot_fv": "Fair Value\n(white = current price)",
        "plot_ret": "Annual Return\n(white = {r:.0f}% target)",
        "plot_xlabel": "Growth g (%)", "plot_ylabel": "Exit PE",
        "plot_fv_cb": "Fair Value ($)", "plot_ret_cb": "Annual Return (%)",
        "plot_assumption": "Assumption (g={g}%, PE={pe}x)",
        "heatmap": "Sensitivity Heatmap",
        "ai_section": "🤖 AI News Analysis",
        "ticker_input": "Stock Ticker (e.g. META, ADI, GEV)",
        "fetch_btn": "① Fetch Price & EPS",
        "analyze_btn": "② Analyze News with AI",
        "fetching": "Fetching data...",
        "analyzing": "Claude is analyzing news...",
        "no_yf": "⚠️ yfinance not installed. Run: pip install yfinance",
        "no_anthropic": "⚠️ anthropic not installed. Run: pip install anthropic",
        "no_api_key": "⚠️ Enter Anthropic API key in sidebar",
        "fetch_success": "✅ Loaded: ${price:.2f} | EPS ${eps:.2f} | TTM PE {pe:.1f}x",
        "fetch_error": "❌ Could not fetch {ticker}. Check ticker symbol.",
        "news_header": "Recent News",
        "impact_label": "DCF Impact",
        "sentiment_bullish": "🟢 Bullish",
        "sentiment_bearish": "🔴 Bearish",
        "sentiment_neutral": "⚪ Neutral",
        "bull_case": "Bull Case",
        "bear_case": "Bear Case",
        "ai_summary": "AI Summary",
        "macro_regime": "Macro Regime",
        "implied_vs_consensus": "Implied g vs Consensus",
        "deep_tab": "🔬 Deep DCF Analysis",
        "news_tab": "📰 News & Sensitivity",
        "deep_title": "Deep DCF Analysis",
        "deep_macro_label": "Macro context (optional)",
        "deep_macro_placeholder": "e.g. Fed rate cut cycle, trade war tariffs, AI capex cycle...",
        "deep_run_btn": "Run Deep Analysis",
        "deep_running": "Claude is running deep DCF analysis...",
        "deep_no_api": "⚠️ ANTHROPIC_API_KEY environment variable not set",
        "deep_result_header": "Analysis Result",
    },
    "zh": {
        "title": "DCF 市场预判工具 · AI 版",
        "subtitle": "P₀ = EPS × (1+g)ⁿ × PE_exit / (1+r)ⁿ",
        "lang_label": "语言",
        "params": "参数设置",
        "price": "当前股价 ($)",
        "eps": "当前 EPS — TTM ($)",
        "g": "预期年增长率 (g %)",
        "r": "要求年回报率 (r %)",
        "n": "预测年数 (n)",
        "pe_exit": "退出 PE 倍数",
        "mode": "分析模式",
        "mode_reverse": "A — 市场在赌什么？",
        "mode_fair": "B — 股票值多少钱？",
        "mode_sense": "C — 敏感性矩阵",
        "implied_g": "市场隐含增长率",
        "your_g": "你的增长假设",
        "fair_val": "公允价值",
        "premium": "溢价 / 折价",
        "verdict_high": "⚠️  市场比你乐观（隐含 {ig:.1f}% vs 你的 {g:.1f}%）。如果增长只到 {g:.1f}%，股价有下行压力。",
        "verdict_low": "✅  市场比你保守（隐含 {ig:.1f}% vs 你的 {g:.1f}%）。如果增长达到 {g:.1f}%，股价有上行空间。",
        "eps_path": "逐年 EPS 路径",
        "year": "年份", "eps_col": "EPS ($)", "exit_price": "退出股价 ($)", "pv": "折现值 ($)",
        "terminal": "第 {n} 年退出 = ${fp:.2f}（EPS ${fe:.2f} × {pe}x）→ 折现回今天 = ${pv:.2f}（要求 {r:.0f}%/年）",
        "updown": "相对市价的上行/下行",
        "sense_title": "公允价值矩阵 — 敏感性分析",
        "sense_sub": "EPS=${eps:.2f} | r={r:.1f}% | n={n}年 | 当前价=${price:.2f}",
        "growth_axis": "增长率 g (%/年)", "pe_axis": "退出 PE",
        "legend_up": "▲ 低估（>5%）", "legend_flat": "─ 合理区间", "legend_down": "▼ 高估（>5%）",
        "how_to": "📋 财报后怎么用",
        "how_1": "1. 看 EPS beat/miss → 调整 EPS 滑块",
        "how_2": "2. 看管理层 guidance → 调整 g 滑块",
        "how_3": "3. 对比矩阵公允价 vs 市场实际反应",
        "how_4": "4. 市场跌但矩阵低估 → 可能买点",
        "how_5": "5. 市场涨但矩阵高估 → 已透支",
        "plot_title": "DCF 敏感性  |  ${price:.2f}  EPS ${eps:.2f}  n={n}年",
        "plot_fv": "Fair Value\n(white = current price)",
        "plot_ret": "Annual Return\n(white = {r:.0f}% target)",
        "plot_xlabel": "Growth g (%)", "plot_ylabel": "Exit PE",
        "plot_fv_cb": "Fair Value ($)", "plot_ret_cb": "Annual Return (%)",
        "plot_assumption": "当前假设 (g={g}%, PE={pe}x)",
        "heatmap": "敏感性热图",
        "ai_section": "🤖 AI 新闻分析",
        "ticker_input": "股票代码（如 META、ADI、GEV）",
        "fetch_btn": "① 自动拉取股价 & EPS",
        "analyze_btn": "② 用 AI 分析新闻",
        "fetching": "正在拉取数据...",
        "analyzing": "Claude 正在分析新闻...",
        "no_yf": "⚠️ 未安装 yfinance。运行：pip install yfinance",
        "no_anthropic": "⚠️ 未安装 anthropic。运行：pip install anthropic",
        "no_api_key": "⚠️ 请在侧边栏输入 Anthropic API Key",
        "fetch_success": "✅ 已加载：${price:.2f} | EPS ${eps:.2f} | TTM PE {pe:.1f}x",
        "fetch_error": "❌ 无法获取 {ticker}，请检查股票代码",
        "news_header": "最新新闻",
        "impact_label": "DCF 变量影响",
        "sentiment_bullish": "🟢 利多",
        "sentiment_bearish": "🔴 利空",
        "sentiment_neutral": "⚪ 中性",
        "bull_case": "多头逻辑",
        "bear_case": "空头逻辑",
        "ai_summary": "AI 综合判断",
        "macro_regime": "宏观环境",
        "implied_vs_consensus": "隐含 g vs Consensus",
        "deep_tab": "🔬 深度 DCF 分析",
        "news_tab": "📰 新闻 & 敏感性",
        "deep_title": "深度 DCF 分析",
        "deep_macro_label": "宏观背景（可选）",
        "deep_macro_placeholder": "如：美联储降息周期、贸易战关税、AI 资本支出周期...",
        "deep_run_btn": "运行深度分析",
        "deep_running": "Claude 正在进行深度 DCF 分析...",
        "deep_no_api": "⚠️ 未设置 ANTHROPIC_API_KEY 环境变量",
        "deep_result_header": "分析结果",
    }
}
